insert into "menuItems"
     ("restaurantId", "name", "price", "description")
values
     (4, 'DOUBLE-DOUBLE', 3.45, ''),
     (4, 'CHEESEBURGER', 2.40, ''),
     (4, 'HAMBURGER', 2.10, ''),
     (4, 'FRENCH FRIES', 1.60, ''),
     (4, 'DOUBLE-DOUBLE COMBO', 6.70, ''),
     (4, 'CHEESEBURGER COMBO', 5.65, ''),
     (4, 'HAMBURGER COMBO', 5.35, ''),
     (4, 'SMALL SOFT DRINK', 1.50, ''),
     (4, 'MEDIUM SOFT DRINK', 1.65, ''),
     (4, 'LARGE SOFT DRINK', 1.85, ''),
     (4, 'XL SOFT DRINK', 2.05, ''),
     (4, 'SHAKE', 2.15, ''),
     (4, 'COFFEE', 1.35, ''),
     (4, 'MILK', 0.99, ''),
     (3, 'Heavenly Biscuits', 3, 'worth the wait'),
     (3, 'Home Smoked Salmon', 18, 'served with our Chef’s dressing and toasts'),
     (3, 'Chilled Jumbo Shrimp', 26, 'with cocktail and rémoulade sauces'),
     (3, 'Newport Beach Clam Chowder', 8, 'served with bacon crumbles and croutons'),
     (3, 'Caesar Salad', 11, 'grated Reggiano, rustic croutons, our signature Caesar dressing'),
     (3, 'Emerald Kale & Rotisserie Chicken Salad', 18, 'with cashews and sesame miso vinaigrette'),
     (3, 'Chopped Vegetable Salad', 20, 'avocado, beets, grapes, chopped egg, macadamia nuts, fresh herbs'),
     (3, 'Pan-seared Ahi Tuna', 23, 'with almond sauce, and salad of mango, avocado, cucumber, sesame miso dressing'),
     (3, 'Cheeseburger', 17, 'freshly ground chuck steak, served all the way on a toasted bun'),
     (3, 'Ding’s Crispy Chicken Sandwich', 18, 'crispy buttermilk fried chicken, baby Swiss, spicy slaw'),
     (3, 'Rotisserie Chicken', 24, 'herb roasted with pan juices'),
     (3, 'Mustard Barbecue Pork Ribs', 28, 'fall-off-the-bone tender, with our house-made barbecue sauce'),
     (3, 'Rutherford Rib-eye', 50, 'hand-selected and lightly seasoned, with house-made Worcestershire'),
     (3, '‘The Duke’ Filet Mignon', 39, 'usda prime center-cut tenderloin'),
     (3, 'Wild Rice with Champagne Vinaigrette and Almonds', 5, ''),
     (3, 'Coleslaw', 5, ''),
     (3, 'Broccoli with Reggiano', 5, ''),
     (3, 'Heirloom Cauliflower', 5, ''),
     (3, 'Pomme Purée', 5, ''),
     (5, 'Uni Pasta', 27, 'Uni Cream Sauce, Dried Seaweed, Fish Roe, Chives'),
     (5, 'EMC Clam Chowder', 9, 'Clams, Bacon, Potatoes, Celery, Onions, Light Creamy Broth'),
     (5, 'Grilled Oysters', 10, 'Choice of Garlic Butter, Smoke Salt, Rockefeller, or Cajun Garlic'),
     (5, 'Fish Tacos', 5.5, 'Fried or Pan Seared'),
     (5, 'Lobster Ravioli', 21.5, 'Shrimp, Clam , Chardonnay Sauce'),
     (5, 'Blue Crab Lettuce Cups', 15.5, 'Blue Crab, Tomatoes, Bacon, Avocado, Louie Sauce, Butter Lettuce'),
     (5, 'Truffle Sliders', 16.5, 'Angus Beef, Mushrooms, Munster, Truffle Shaving Saunce, Shitake Aioli, Brioche Bun'),
     (6, 'Baconator', 8.99, '1/2 Double Beef , Bacon, Cheese'),
     (6, 'Big Bacon Classic', 6.99, '1/3 Beef , Bacon, Cheese'),
     (6, 'Grilled Chicken Sandwich', 5.49, 'Grilled Chicken, Lettuce, Tomatoes, Onion'),
     (6, 'Southwest Avocado Chicken Salad', 14.5, 'Lettuce, Avocado, Chicken, Tomatoes, Southwest Sauce'),
     (6, '4 for $5', 5, 'Chicken Sandwich, 10pc nuggets, french fries, and a drink'),
     (1, 'Pad Thai', 9.95, 'Stir-fried rice noodles with our special seasoning, egg, green onions, bean sprouts, and sprinkled with ground peanuts. Gluten-free'),
     (1, 'Pad See Ewe', 9.95, 'Soft wide rice noodles stir-fried with sweet black soy sauce, egg, broccoli, mushrooms, carrots, and baby corn. Sweet and savory.'),
     (1, 'Pad Kee Mow', 9.95, 'Soft wide rice noodles stir-fried with garlic, Thai basil, sprouts, carrots, and onions. Served over lettuce. Savory, tangy, delicious!'),
     (1, 'Pineapple Fried Rice', 10.95, 'Curry-seasoned fried rice with pineapple, onions, carrots, cashew nuts and raisins. Gluten-free'),
     (1, 'Thai Spice Fried Rice ', 9.95, 'Our signature fried rice with a tangy and savory seasoning, Thai basil, bean sprouts, carrots, onions, and garlic'),
     (1, 'Chicken Yellow Curry', 10.95, 'A classic favorite, tender chicken and potato cooked in yellow curry and Thai coconut milk. Served with rice. Gluten-free'),
     (1, 'Green Curry ', 11.95, 'Tender beef, white meat chicken, or tofu with bell pepper, bamboo shoots, zucchini, peas and carrots in green curry and Thai coconut milk. Served with rice on the side. Gluten-free'),
     (1, 'Mango with Sweet Sticky Rice', 4.95, 'Seasonal'),
     (1, 'Thai Iced Tea', 3.50, 'Traditional Thai iced tea cold-brewed on site. Non-dairy creamer added to create a sweet delicious drink'),
     (1, 'Thai Iced Coffee', 3.50, 'Iced dark cold-brewed coffee Thai-style with non-dairy creamer added'),
     (1, 'Thai Chicken Salad', 12.95, 'Seasoned chicken breast with lettuce, cucumbers, broccoli, tomatoes, onions, carrots, and bell pepper topped with crunchy noodles, choice of dressing: Zesty Lemon, peanut sauce or honey ranch'),
     (1, 'Thai Beef Salad', 11.95, 'Sliced tender beef with cucumbers, tomatoes, onions, carrots, celery, and tossed with our Thai citrus dressing. Beef is NOT gluten-free'),
     (1, 'Tom Ka Kai', 6.25, 'Sliced chicken breast with mushrooms, celery, white onion, herbs and seasoning in a traditional Thai coconut milk broth'),
     (2, 'Margherita Pizza', 16.50, 'Tomato sauce + house made mozzarella + basil'),
     (2, 'Pepperoni + Sausage Pizza', 18.00, 'Ricotta + fresh mozzarella + tomato + garlic + basil'),
     (2, 'Fig + stracchino', 17.00, 'Garlic + hot honey + arugula'),
     (2, 'Cheese Pizza', 14.00, 'Cheese Pizza'),
     (2, 'Vegan Pizza', 14.50, 'Chefs whim'),
     (2, 'Clam + squid ink linguine', 24.00, 'Charred tomato + fennel soffritto + creme fraiche'),
     (2, 'Bucatini amatriciana', 19.50, 'Guanciale + tomato + onion + chili + pecorino'),
     (2, 'Rigatoni Bolognese', 20.00, 'Veal + pork + lemon ricotta + grana padano'),
     (2, 'Cucina burger', 19.00, 'Taleggio + port wine onion + porcini aioli + brioche bun + parmesan fries'),
     (2, 'Olive oil cake', 10.00, 'Seasonal fruit + pistachio whip'),
     (2, 'Chocolate panna cotta', 9.00, 'Mascarpone crema + cacao nib'),
     (2, 'Cannellini bean hummus', 12.00, 'Sicilian pesto + pistachio + market vegetable + baguette'),
     (2, 'Charred Octopus', 16.50, 'Gigante bean + fennel + lemon yogurt + brown butter vinaigrette'),
     (8, 'Crispy Cauliflower', 8.45, 'fresh cauliflower florets in panko breading choice of buffalo-style or orange dipping sauce'),
     (8, 'Kids Veggie Burger', 8.95, 'House made veggie burger with lettuce, tomato, pickles and ketchup on a sesame bun'),
     (8, 'Pesto Zucchini Noodles', 11.95, 'lightly seared zucchini noodles in basil pesto with arugula, parmesan, spicy italian sausage crumbles and roasted baby tomatoes'),
     (8, 'Far East Bowl', 12.50, 'choice of grilled tempeh or crispy sesame chickin with  wild rice, broccolini, pickled vegetables, fresh herbs, and thai coconut curry sauce'),
     (8, 'Greek Mezze Salad', 10.15, 'vg lettuce blend, tossed in our house vinaigrette with fresh herbs, marinated gigande beans, feta, roasted baby tomatoes, kalamata olives, cucumber, and 3-seed crunch'),
     (8, 'Catalina Taco Salad', 11.95, 'achiote crumbles, lettuce mix, cabbage, tomato corn salsa, ranchero beans, jicama and avocado, tossed in catalina dressing'),
     (8, 'House Veggie Burger', 12.00, 'wild rice mushroom burger, arugula, baby tomatoes, basil aioli, pickled onion on a whole grain sesame bun'),
     (8, 'Sweet Potato Fries', 5.45, 'served with ketchup and chipotle aioli'),
     (8, 'The Caprese', 8.20, 'layers of fresh tomato, farmers cheese, arugula, basil pesto, soft wheat roll'),
     (8, '7 Layer Burrito', 7.95, 'our play on a classic: layers of ranchero beans, wild rice, romaine lettuce, pico de gallo, mashed avocado, shredded cheddar cheese, chipotle cream, all wrapped in a warmed flour tortilla'),
     (8, 'La Colombe- Oat Milk Latte', 4.75, 'oat milk latte'),
     (8, 'Oatmeal Cookie', 2.75, 'Enriched flour, brown sugar, raisins, oats, natural vanilla flour, cinnamon'),
     (8, 'Carrot Cake', 4.25, 'Fresh carrots, walnuts, VG cream cheese frosting'),
     (8, 'Chocolate Parfait', 4.50, 'Layers of chocolate pudding and chocolate cookie crumbles, crema, and chocolate syrup');
